language: python
python:
<<<<<<< HEAD
  - "2.7"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -e .
script:
 - py.test
=======
 - "2.7"
# command to install dependencies
install:
 - pip install -e .
script:
- py.test
>>>>>>> removed
